[package]
name = "ef74"
version = "0.1.0"
authors = ["koka <koka.code@gmail.com>"]
edition = "2018"
autobins = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
